apiVersion: v1beta3
id: jboss-eap
kind: Service
metadata:
  name: jboss-eap
  context: docker-jboss-eap-lab
spec:
  selector: 
    name: jboss-eap
  ports:
    - name: http
      port: 8081
      targetPort: 8080
    - name: admin
      port: 9990
      targetPort: 9990
    - name: management
      port: 9999
      targetPort: 9999

