apiVersion: v1beta3
id: jboss-eap-server-rc
kind: ReplicationController
metadata:
  name: jboss-eap-server
spec: 
  replicas: 1
  selector: 
    name: jboss-eap-server
  template:
    metadata:
      name: jboss-eap-server
      labels: 
        name: jboss-eap-server
        context: docker-jboss-eap-lab
    spec:
      containers: 
        - name: jboss-eap-server
          image: pmuir/jboss-eap-postgres-ticket-monster:1.0
          ports: 
            - containerPort: 9990
              hostPort: 9900
            - containerPort: 8080
              hostPort: 9080
            - containerPort: 9999
              hostPort: 9999
